Instance,Runtime (seconds),Feasible,Profit,Error
lrc33.txt,0.49,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', 'Instances/lrc33.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/vrp-competition-submissions/vrp-competition-back-benchers/Group3/main.py"", line 71, in <module>
    instance = vrplib.read_instance(""../../Instances/Test/X-n101-k25.vrp"")
  File ""/usr/local/lib/python3.10/dist-packages/vrplib/read/read_instance.py"", line 29, in read_instance
    with open(path, ""r"") as fi:
FileNotFoundError: [Errno 2] No such file or directory: '../../Instances/Test/X-n101-k25.vrp'
]"
lrc34.txt,0.50,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', 'Instances/lrc34.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/vrp-competition-submissions/vrp-competition-back-benchers/Group3/main.py"", line 71, in <module>
    instance = vrplib.read_instance(""../../Instances/Test/X-n101-k25.vrp"")
  File ""/usr/local/lib/python3.10/dist-packages/vrplib/read/read_instance.py"", line 29, in read_instance
    with open(path, ""r"") as fi:
FileNotFoundError: [Errno 2] No such file or directory: '../../Instances/Test/X-n101-k25.vrp'
]"
